name: BukkitLandGenerator
main: me.Morlok8k.BukkitLandGenerator.BukkitLandGenerator
version: 0.1.0 Alpha - Build 11 - CB v1000 -(Preview Release) 
author: Morlok8k

commands:
    BLGgen:
        description: Generate Land in a square of X Chunks around player position
        usage: /BLGgen <Number of Chunks in a Square Diameter>
        